[Common]
# 默认监听端口 (4 + 学号后四位 3593)
UDPPort = 43593
# 日志文件存放路径
LogPath = gbn_project.log

[GBN]
# 发送窗口大小 (SWSize)
SWSize = 4
# 起始 PDU 的序号 (InitSeqNo)
InitSeqNo = 1
# 超时定时器值 (单位：毫秒)
Timeout = 200
# 每个 PDU 的数据载荷大小 (DataSize，单位：字节)
DataSize = 4096

[Simulation]
# PDU 丢失率 (%)
LostRate = 1.0
# PDU 错误率 (%)
ErrorRate = 1.0
